# Generated by Django 5.2.4 on 2026-06-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psi', models.FloatField()),
                ('depth', models.FloatField()),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='fleet.tyre')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='fleet.vehicle')),
            ],
        ),
    ]
